### ISSUE TITLE
Ember build failing after installing this

### ISSUE THREAD

**Issue by nabong04** [auth0/auth0-ember-simple-auth#47]
Anyone knows what might be failing my builds? Here's how my terminal looks like:
```
ember server

Just getting started with Ember? Please visit http://localhost:4200/ember-getting-started to get going

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat 'C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\tmp\source_map_concat-input_base_path-8tKsUftu.tmp\0\bower_components\auth0-lock\build\auth0-lock.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:112:65)
    at C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:21:10)
    at new ConcatWithMaps (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\broccoli-concat\concat.js:22:17)
    at module.exports (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\node_modules\broccoli-concat\index.js:26:10)
    at EmberApp.concatFiles (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\lib\broccoli\ember-app.js:348:10)
    at EmberApp.javascript (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\lib\broccoli\ember-app.js:1214:12)
    at EmberApp.toArray (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\lib\broccoli\ember-app.js:1566:10)
    at EmberApp.toTree (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\lib\broccoli\ember-app.js:1588:30)
    at module.exports (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\ember-cli-build.js:23:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\Nabong\Desktop\Workspace\auth0_fix_from_scratch\node_modules\ember-cli\lib\models\builder.js:54:19)

```

**Comment by nabong04** [comment]
I found i needed to do `ember generate auth0-ember-simple-auth` to install both jsrsasign and auth0-lock. This has solved my issue
