### ISSUE TITLE
"Error: ENOENT: no such file or directory" for auth0-lock.js 

### ISSUE THREAD

**Issue by jtsom** [auth0/auth0-ember-simple-auth#54]
I know this has been reported a couple times, but I'm running into this issue. Following the directions on the Auth0 site for an Ember app, I'm seeing these errors when trying to run the app:

```
he Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/John/Dev/Javascript/Ember/auth0test/tmp/source_map_concat-input_base_path-l2Q4sVSH.tmp/0/bower_components/auth0-lock/build/auth0-lock.js'
    at Object.fs.statSync (fs.js:898:18)
    at FSMonitor._measure (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.statSync (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at Concat.keyForFile (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:109:65)
    at /Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:521:7)

The broccoli plugin was instantiated at:
    at Concat.Plugin (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at Concat.CachingWriter [as constructor] (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:18:10)
    at new Concat (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:32:17)
    at module.exports (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/lib/broccoli/ember-app.js:370:10)
    at EmberApp._concatFiles (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/lib/broccoli/ember-app.js:383:15)
    at EmberApp.javascript (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/lib/broccoli/ember-app.js:1269:12)
    at EmberApp.toArray (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/lib/broccoli/ember-app.js:1640:10)
    at EmberApp.toTree (/Users/John/Dev/Javascript/Ember/auth0test/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:30)
    at module.exports (/Users/John/Dev/Javascript/Ember/auth0test/ember-cli-build.js:23:14)
```

Per the previous reports, I did run the command `ember generate scaffold-auth0` but it made no difference. It doesn't look like that command installs anything in the bower.json config file or any bower packages.

**Comment by jtsom** [comment]
Sigh.

Nevermind. Didn't realize there are TWO ember generate commands needed

'ember generate scaffold-auth0'
and
`ember generate auth0-ember-simple-auth`
